---
- hosts: all
  gather_facts: yes
  become: yes
  vars_files:
    - vars/main.yml
  handlers:
    - include: handlers/main.yml
  tasks:
    - include: tasks/main.yml

    - debug: var=rhel7cis_section1
    - include_role:
        name: section_1
      when: rhel7cis_section1 == true

    - debug: var=rhel7cis_section2
    - include_role:
        name: section_2
      when: rhel7cis_section2 == true

    - debug: var=rhel7cis_section3
    - include_role:
        name: section_3
      when: rhel7cis_section3 == true

    - debug: var=rhel7cis_section4
    - include_role:
        name: section_4
      when: rhel7cis_section4 == true

    - debug: var=rhel7cis_section5
    - include_role:
        name: section_5
      when: rhel7cis_section5 == true

    - debug: var=rhel7cis_section6
    - include_role:
        name: section_6
      when: rhel7cis_section6 == true