---

- name: "3.5.1.1 Ensure FirewallD is installed"
  yum:
      name: ['firewalld', 'iptables']
      state: present
      update_cache: true
  when:
      - rhel7cis_rule_3_5_1_1

- name: "3.5.1.2 Ensure iptables-services not installed with firewalld"
  package:
      name: iptables-services
      state: absent
  when:
      - rhel7cis_rule_3_5_1_2

- name: "3.5.1.3 Ensure nftables either not installed or masked with firewalld"
  package:
      name: nftables
      state: absent
  when:
      - rhel7cis_rule_3_5_1_3

- name: "3.5.1.4 Ensure firewalld service is enabled and running"
  systemd:
      name: firewalld
      state: started
      enabled: true
  when:
      - rhel7cis_rule_3_5_1_4

- name: "3.5.1.5 Ensure firewalld default zone is set"
  block:
      - name: "3.5.1.5 Ensure default zone is set | Get status"
        command: firewall-cmd --get-default-zone
        changed_when: no
        register: current_default_zone

      - name: "3.5.1.5 Ensure default zone is set | Set parameter"
        command: firewall-cmd --set-default-zone="{{ rhel7cis_default_zone }}"
        when:
            - current_default_zone.stdout != rhel7cis_default_zone
        ignore_errors: "{{ ansible_check_mode }}"
  when:
      - rhel7cis_rule_3_5_1_5

- name: "3.5.1.6 Ensure network interfaces are assigned to appropriate zone"
  block:
      - name: "3.5.1.6 Ensure network interfaces are assigned to appropriate zone | Get list of interfaces and policies"
        shell: "nmcli -t connection show | awk -F: '{ if($4){print $4} }' | while read INT; do firewall-cmd --get-active-zones | grep -B1 $INT; done"
        register: rhel7cis_3_5_1_6_interfacepolicy
        changed_when: no
        become: yes
        ignore_errors: true

      - name: "3.5.1.6 Ensure network interfaces are assigned to appropriate zone | Get list of interfaces and policies | Show the interface to policy"
        debug:
            msg:
                - "The items below are the policies tied to the interfaces, please correct as needed"
                - "{{ rhel7cis_3_5_1_6_interfacepolicy.stdout_lines }}"
        ignore_errors: "{{ ansible_check_mode }}"
  when:
      - rhel7cis_rule_3_5_1_6

- name: "3.5.1.7 Ensure firewalld drops unnecessary services and ports"
  block:
      - name: "3.5.1.7 Ensure firewalld drops unnecessary services and ports | Get list of services and ports"
        shell: "firewall-cmd --get-active-zones | awk '!/:/ {print $1}' | while read ZN; do firewall-cmd --list-all --zone=$ZN; done"
        register: rhel7cis_3_5_1_7_servicesport
        become: true
        changed_when: no

      - name: "3.5.1.7 Ensure firewalld drops unnecessary services and ports | Show services and ports"
        debug:
            msg:
                - "The items below are the services and ports that are accepted, please correct as needed"
                - "{{ rhel7cis_3_5_1_7_servicesport.stdout_lines }}"
        ignore_errors: "{{ ansible_check_mode }}"
  when:
      - rhel7cis_rule_3_5_1_7