---

- name: "6.1.2 Ensure permissions on /etc/passwd are configured"
  file:
    dest: /etc/passwd
    owner: root
    group: root
    mode: 0644
  when:
  - rhel7cis_rule_6_1_2

- name: "6.1.3 Ensure permissions on /etc/passwd- are configured"
  file:
    dest: /etc/passwd-
    owner: root
    group: root
    mode: 0644
  when:
  - rhel7cis_rule_6_1_3

- name: "6.1.4 Ensure permissions on /etc/shadow are configured"
  file:
    dest: /etc/shadow
    owner: root
    group: root
    mode: 0000
  when:
  - rhel7cis_rule_6_1_4

- name: "6.1.5 Ensure permissions on /etc/shadow- are configured"
  file:
    dest: /etc/shadow-
    owner: root
    group: root
    mode: 0000
  when:
  - rhel7cis_rule_6_1_5

- name: "6.1.6 Ensure permissions on /etc/gshadow- are configured"
  file:
    dest: /etc/gshadow-
    owner: root
    group: root
    mode: 0000
  when:
  - rhel7cis_rule_6_1_6

- name: "6.1.7 Ensure permissions on /etc/gshadow are configured"
  file:
    dest: /etc/gshadow
    owner: root
    group: root
    mode: 0000
  when:
  - rhel7cis_rule_6_1_7

- name: "6.1.8 Ensure permissions on /etc/group are configured"
  file:
    dest: /etc/group
    owner: root
    group: root
    mode: 0644
  when:
  - rhel7cis_rule_6_1_8

- name: "6.1.9 Ensure permissions on /etc/group- are configured"
  file:
    dest: /etc/group-
    owner: root
    group: root
    mode: 0644
  when:
  - rhel7cis_rule_6_1_9

- name: "6.1.10 Ensure no world writable files exist"
  block:
  - name: "6.1.10 Ensure no world writable files exist | Get list of world-writable files"
    shell: df --local -P | awk {'if (NR!=1) print $6'} | xargs -I '{}' find '{}' -xdev -type f -perm -0002
    become: yes
    failed_when: false
    changed_when: false
    async: 7200
    poll: 60
    ignore_errors: "{{ ansible_check_mode }}"
    register: rhel_07_6_1_10_perms

  - name: "6.1.10 Ensure no world writable files exist | Alert no world-writable files exist"
    debug:
      msg: "Good news! We have not found any world-writable files on your system"
    failed_when: false
    changed_when: false
    when:
    - rhel_07_6_1_10_perms.results is not defined

  - name: "6.1.10 Ensure no world writable files exist | Adjust world-writable files if they exist (Configurable)"
    file:
      path: '{{ item }}'
      mode: o-w
      state: touch
    async: 7200
    poll: 60
    ignore_errors: "{{ ansible_check_mode }}"
    with_items: "{{ rhel_07_6_1_10_perms.stdout_lines }}"
    when:
    - rhel_07_6_1_10_perms.results is defined
    - rhel7cis_no_world_write_adjust
  when:
  - rhel7cis_rule_6_1_10

- name: "6.1.11 Ensure no unowned files or directories exist"
  block:
  - name: "6.1.11 Ensure no unowned files or directories exist | Finding all unowned files or directories"
    shell: df --local -P | awk {'if (NR!=1) print $6'} | xargs -I '{}' find '{}' -xdev -nouser
    become: yes
    async: 7200
    poll: 60
    failed_when: no
    changed_when: no
    ignore_errors: "{{ ansible_check_mode }}"
    register: rhel_07_6_1_11_audit
    
  - name: "6.1.11 Ensure no unowned files or directories exist | Alert no unowned files or directories exist"
    debug:
      msg: "Good news! We have not found any unowned files or directories on your system"
    failed_when: false
    changed_when: false
    when:
    - rhel_07_6_1_11_audit.results is not defined

  - name: "6.1.11 Ensure no unowned files or directories exist | Displaying any unowned files or directories"
    debug:
      msg: "Warning - Manual intervention is required -- missing owner on items in {{ rhel_07_6_1_11_audit.stdout_lines }}"
    when:
    - rhel_07_6_1_11_audit.results is defined
  when:
  - rhel7cis_rule_6_1_11

- name: "6.1.12 Ensure no ungrouped files or directories exist"
  block:
  - name: "6.1.12 Ensure no ungrouped files or directories exist | Finding all ungrouped files or directories"
    shell: df --local -P | awk '{if (NR!=1) print $6}' | xargs -I '{}' find '{}' -xdev -nogroup
    become: yes
    async: 7200
    poll: 60
    failed_when: no
    changed_when: no
    ignore_errors: "{{ ansible_check_mode }}"
    register: rhel_07_6_1_12_audit
    
  - name: "6.1.12 Ensure no ungrouped files or directories exist | Alert no ungrouped files or directories exist"
    debug:
      msg: "Good news! We have not found any ungrouped files or directories on your system"
    failed_when: false
    changed_when: false
    when:
    - rhel_07_6_1_12_audit.results is not defined

  - name: "6.1.12 Ensure no ungrouped files or directories exist | Displaying any ungrouped files or directories"
    debug:
      msg: "Warning - Manual intervention is required -- missing group on items in {{ rhel_07_6_1_12_audit.stdout_lines }}"
    when:
    - rhel_07_6_1_12_audit.results is defined
  when:
  - rhel7cis_rule_6_1_12

- name: "6.1.13 Audit SUID executables"
  block:
  - name: "6.1.13 Audit SUID executables | Find all SUID executables"
    shell: df --local -P | awk '{if (NR!=1) print $6}' | xargs -I '{}' find '{}' -xdev -type f -perm -4000
    become: yes
    async: 7200
    poll: 60
    failed_when: no
    changed_when: no
    ignore_errors: "{{ ansible_check_mode }}"
    register: rhel_07_6_1_13_audit
    
  - name: "6.1.13 Audit SUID executables | Alert no SUID executables exist"
    debug:
      msg: "Good news! We have not found any SUID executable files on your system"
    failed_when: false
    changed_when: false
    when:
    - rhel_07_6_1_13_audit.results is not defined

  - name: "6.1.13 Audit SUID executables | Displaying any executable SUID files"
    debug:
      msg: "Warning - Manual intervention is required -- SUID set on items in {{ rhel_07_6_1_13_audit.stdout_lines }}"
    when:
    - rhel_07_6_1_13_audit.results is defined
  when:
  - rhel7cis_rule_6_1_13

- name: "6.1.14 Audit SGID executables"
  block:
  - name: "6.1.14 Audit SGID executables | Find all SGID executables"
    shell: df --local -P | awk '{if (NR!=1) print $6}' | xargs -I '{}' find '{}' -xdev -type f -perm -2000
    become: yes
    async: 7200
    poll: 60
    failed_when: no
    changed_when: no
    ignore_errors: "{{ ansible_check_mode }}"
    register: rhel_07_6_1_14_audit
    
  - name: "6.1.14 Audit SGID executables | Alert no SGID executables exist"
    debug:
      msg: "Good news! We have not found any SGID executable files on your system"
    failed_when: false
    changed_when: false
    when:
    - rhel_07_6_1_14_audit.results is not defined

  - name: "6.1.14 Audit SGID executables | Displaying any executable SGID files"
    debug:
      msg: "Warning - Manual intervention is required -- SGID set on items in {{ rhel_07_6_1_14_audit.stdout_lines }}"
    when:
    - rhel_07_6_1_14_audit.results is defined
  when:
  - rhel7cis_rule_6_1_14