---

- name: "5.5.1.1 Ensure password expiration is 365 days or less"
  block:
    - name: "5.5.1.1 Ensure password expiration is 365 days or less | Set parameter in login.defs"
      lineinfile:
        state: present
        dest: /etc/login.defs
        regexp: '^PASS_MAX_DAYS'
        line: "PASS_MAX_DAYS {{ rhel7cis_pass['max_days'] }}"

    - name: "5.5.1.1 Ensure password expiration is 365 days or less | Find users"
      shell: "grep -E '^[^:]+:[^!*]' /etc/shadow | cut -d: -f1"
      register: users
    
    - name: "5.5.1.1 Ensure password expiration is 365 days or less | Modify user parameter"
      command: chage --maxdays 99999 {{ item }}
      loop: "{{ users.stdout_lines }}"
      ignore_errors: "{{ ansible_check_mode }}"
  when:
  - rhel7cis_rule_5_5_1_1

- name: "5.5.1.2 Ensure minimum days between password changes is configured"
  block:
    - name: "5.5.1.2 Ensure minimum days between password changes is configured | Set parameter in login.defs"
      lineinfile:
        state: present
        dest: /etc/login.defs
        regexp: '^PASS_MIN_DAYS'
        line: "PASS_MIN_DAYS {{ rhel7cis_pass['min_days'] }}"
    
    - name: "5.5.1.2 Ensure minimum days between password changes is configured | Modify user parameter"
      command: "chage --mindays 0 {{ item }}"
      loop: "{{ users.stdout_lines }}"
      ignore_errors: "{{ ansible_check_mode }}"
  when:
  - rhel7cis_rule_5_5_1_2

- name: "5.5.1.3 Ensure password expiration warning days is 7 or more"
  lineinfile:
    state: present
    dest: /etc/login.defs
    regexp: '^PASS_WARN_AGE'
    line: "PASS_WARN_AGE {{ rhel7cis_pass['warn_age'] }}"
  when:
  - rhel7cis_rule_5_5_1_3

- name: "5.5.1.4 Ensure inactive password lock is 30 days or less"
  block:
      - name: "5.5.1.4 Ensure inactive password lock is 30 days or less | Set default inactive setting"
        lineinfile:
            path: /etc/default/useradd
            regexp: '^INACTIVE='
            line: "INACTIVE={{ rhel7cis_inactivelock['lock_days'] }}"
            state: present

      - name: "5.5.1.4 Ensure inactive password lock is 30 days or less | Getting user list"
        # shell: 'egrep ^[^:]+:[^\!*] /etc/shadow | cut -d: -f1'
        shell: "egrep ^[^:]+:[^\\!*] /etc/shadow | awk -F: '{print $1 \",\" $7}' | egrep -v  ',\\d|,[1-2][0-9]|,30|{{ rhel7cis_inactive_whitelist | join('|') }}' | cut -d , -f1"
        register: rhel_07_5_5_1_4_audit
        changed_when: no

      - name: "5.5.1.4 | L1 | PATCH | Ensure inactive password lock is 30 days or less | Apply Inactive setting to existing accounts"
        shell: "chage --inactive {{ rhel7cis_inactivelock.lock_days }} {{ item }}"
        with_items:
            - "{{ rhel_07_5_5_1_4_audit.stdout_lines }}"
        when:
            - rhel_07_5_5_1_4_audit.stdout | length > 0
        ignore_errors: "{{ ansible_check_mode }}"
  when:
      - rhel7cis_rule_5_5_1_4

- name: "5.5.1.5 Ensure all users last password change date is in the past"
  block:
      - name: "5.5.1.5 Ensure all users last password change date is in the past | Get current date in Unix Time"
        shell: echo $(($(date --utc --date "$1" +%s)/86400))
        failed_when: no
        changed_when: no
        register: rhel7cis_5_5_1_5_current_unix_time

      - name: "5.5.1.5 Ensure all users last password change date is in the past | Get list of users with last changed pw date in the future"
        shell: "cat /etc/shadow | awk -F: '{if($3>{{ rhel7cis_5_5_1_5_current_unix_time.stdout }})print$1}'"
        register: rhel7cis_5_5_1_5_user_list
        ignore_errors: "{{ ansible_check_mode }}"

      - name: "5.5.1.5 Ensure all users last password change date is in the past | Alert no pw change in the future exist"
        debug:
            msg: "Good News! All accounts have PW change dates that are in the past"
        when: rhel7cis_5_5_1_5_user_list.stdout | length == 0
        ignore_errors: "{{ ansible_check_mode }}"

      - name: "5.5.1.5 Ensure all users last password change date is in the past | Alert on accounts with pw change in the future"
        debug:
            msg: "Warning! The following accounts have the last PW change date in the future: {{ rhel7cis_5_5_1_5_user_list.stdout_lines }}"
        when:
            - rhel7cis_5_5_1_5_user_list.stdout | length > 0
            - not rhel7cis_futurepwchgdate_autofix
        ignore_errors: "{{ ansible_check_mode }}"

      - name: "5.5.1.5 Ensure all users last password change date is in the past | Fix accounts with pw change in the future"
        shell: passwd --expire {{ item }}
        when:
            - rhel7cis_5_5_1_5_user_list | length > 0
            - rhel7cis_futurepwchgdate_autofix
        with_items:
            - "{{ rhel7cis_5_5_1_5_user_list.stdout_lines }}"
        ignore_errors: "{{ ansible_check_mode }}"
  when:
      - rhel7cis_rule_5_5_1_5
      - ansible_facts['distribution'] == "RedHat" or ansible_facts['distribution'] == "CentOS"

- name: "5.5.2 Ensure system accounts are secured"
  block:
      - name: "5.5.2 Ensure system accounts are secured | Set nologin"
        user:
            name: "{{ item.id }}"
            shell: /usr/sbin/nologin
        loop: "{{ rhel7cis_passwd }}"
        become: true
        when:
            - item.id != "root"
            - item.id != "sync"
            - item.id != "shutdown"
            - item.id != "halt"
            - item.gid < rhel7cis_int_gid
            - item.shell != "      /bin/false"
            - item.shell != "      /usr/sbin/nologin"

      - name: "5.5.2 Ensure system accounts are secured | Lock accounts"
        user:
            name: "{{ item.id }}"
            password_lock: true
        loop: "{{ rhel7cis_passwd }}"
        become: true
        when:
            - item.id != "halt"
            - item.id != "shutdown"
            - item.id != "sync"
            - item.id != "root"
            - item.gid < rhel7cis_int_gid
            - item.shell != "      /bin/false"
            - item.shell != "      /usr/sbin/nologin"
  when:
      - rhel7cis_rule_5_5_2

- name: "5.5.3 Ensure default group for the root account is GID 0"
  command: usermod -g 0 root
  changed_when: no
  failed_when: no
  when:
  - rhel7cis_rule_5_5_3

- name: "5.5.4 Ensure default user shell timeout is configured"
  blockinfile:
    create: yes
    mode: 0644
    dest: "{{ item.dest }}"
    state: "{{ item.state }}"
    marker: "# {mark} ANSIBLE MANAGED"
    block: |
      # Set session timeout - CIS ID RHEL-07-5.4.4
      TMOUT={{ rhel7cis_shell_session_timeout.timeout }}
      readonly TMOUT
      export TMOUT
  loop:
  - dest: "{{ rhel7cis_shell_session_timeout.file }}"
    state: present
  - dest: /etc/profile
    state: "{{ (rhel7cis_shell_session_timeout.file == '/etc/profile') | ternary('present', 'absent') }}"
  when:
  - rhel7cis_rule_5_5_4

- name: "5.5.5 Ensure default user umask is configured | RHEL/CentOS"
  block:
  - name: "5.5.5 Ensure default user umask is configured | Set umask for /etc/bashrc"
    replace:
      path: /etc/bashrc
      regexp: '(^\s+umask) 002'
      replace: '\1 027'

  - name: "5.5.5 Ensure default user umask is configured | Set umask for /etc/profile"
    replace:
      path: /etc/profile
      regexp: '(^\s+umask) 002'
      replace: '\1 027'
  when:
  - rhel7cis_rule_5_5_5
  - ansible_facts['distribution'] == "RedHat" or ansible_facts['distribution'] == "CentOS"

- name: "5.5.5 Ensure default user umask is configured | Ubuntu"
  block:
  - name: "5.5.5 Ensure default user umask is configured | Set umask for /etc/bash.bashrc | Replace existing string"
    replace:
      path: /etc/bash.bashrc
      regexp: '(\s+umask).*'
      replace: '\1 027'

  - name: "5.5.5 Ensure default user umask is configured | Set umask for /etc/bash.bashrc | Add new string"
    lineinfile:
      path: /etc/bash.bashrc
      line: "umask 027"
      state: present
  when:
  - rhel7cis_rule_5_5_5
  - ansible_facts['distribution'] == "Ubuntu"