---

- name: "1.2.1 Ensure GPG keys are configured | RHEL/CentOS"
  block:
      - name: "1.2.1 Ensure GPG keys are configured | RedHat"
        command: gpg --quiet --with-fingerprint /etc/pki/rpm-gpg/RPM-GPG-KEY-{{ ansible_distribution|lower }}-release
        when:
            - ansible_distribution == "RedHat"

      - name: "1.2.1 Ensure GPG keys are configured | CentOS"
        command: gpg --quiet --with-fingerprint /etc/pki/rpm-gpg/RPM-GPG-KEY-{{ ansible_distribution }}-{{ ansible_distribution_major_version }}
        when:
            - ansible_distribution == "CentOS"
  when:
      - rhel7cis_rule_1_2_1

- name: "1.2.1 Ensure GPG keys are configured | Ubuntu"
  command: apt-key list
  when: 
      - rhel7cis_rule_1_2_1
      - ansible_facts['distribution'] == "Ubuntu"

- name: "1.2.2 Ensure package manager repositories are configured | RHEL/CentOS"
  block:
      - name: "1.2.2 Ensure package manager repositories are configured | RHEL/CentOS"
        shell: yum repolist
        changed_when: no
        register: repolist
        args:
          warn: no

      - name: "1.2.2 Ensure package manager repositories are configured | RHEL/CentOS"
        debug:
            msg:
                - "Please check against site policy repos listed below match expected:"
                - "{{ repolist.stdout_lines }}"
        ignore_errors: "{{ ansible_check_mode }}"
  when:
      - rhel7cis_rule_1_2_2
      - ansible_facts['distribution'] == "RedHat" or ansible_facts['distribution'] == "CentOS"

- name: "1.2.2 Ensure package manager repositories are configured | Ubuntu"
  block:
      - name: "1.2.2 Ensure package manager repositories are configured | Ubuntu"
        shell: apt-cache policy
        changed_when: no
        register: repolist
        args:
          warn: no

      - name: "1.2.2 Ensure package manager repositories are configured | Ubuntu"
        debug:
            msg:
                - "Please check against site policy repos listed below match expected:"
                - "{{ repolist.stdout_lines }}"
        ignore_errors: "{{ ansible_check_mode }}"
  when:
      - rhel7cis_rule_1_2_2
      - ansible_facts['distribution'] == "Ubuntu"

- name: "1.2.3 Ensure gpgcheck is globally activated"
  block:
      - name: "1.2.3 Ensure gpgcheck is globally activated"
        find:
            paths: /etc/yum.repos.d
            patterns: "*.repo"
        register: yum_repos
        changed_when: no

      - name: "1.2.3 Ensure gpgcheck is globally activated"
        replace:
            path: "{{ item.path }}"
            regexp: "^gpgcheck=0"
            replace: "gpgcheck=1"
        loop: "{{ yum_repos.files }}"
  when:
      - rhel7cis_rule_1_2_3
      - ansible_facts['distribution'] == "RedHat" or ansible_facts['distribution'] == "CentOS"

- name: "1.2.4 Ensure Red Hat Subscription Manager connection is configured"
  shell: subscription-manager identity
  changed_when: no
  failed_when: no
  when:
      - ansible_distribution == "RedHat"
      - rhel7cis_rule_1_2_4

- name: "1.2.5 Disable the rhnsd Daemon"
  service:
      name: rhnsd
      state: stopped
      enabled: no
  when:
      - ansible_distribution == "RedHat" and not rhel7cis_rhnsd_required
      - rhel7cis_rule_1_2_5
      - ansible_facts['distribution_major_version'] == "7"