---

- name: "4.2.1.1 Ensure rsyslog is installed"
  package:
    name: "{{ rhel7cis_syslog }}"
    state: present
  when:
    - rhel7cis_rule_4_2_1_1

- name: "4.2.1.2 Ensure rsyslog Service is enabled and running"
  service:
    name: rsyslog
    enabled: yes
    state: started
  when:
    - rhel7cis_rule_4_2_1_2
    - rhel7cis_syslog == 'rsyslog'

- name: "4.2.1.3 Ensure rsyslog default file permissions configured"
  lineinfile:
    dest: /etc/rsyslog.conf
    regexp: '^\$FileCreateMode'
    line: '$FileCreateMode 0640'
  notify: restart rsyslog
  when:
    - rhel7cis_rule_4_2_1_3

- name: "4.2.1.4 Ensure logging is configured"
  block:
      - name: "4.2.1.4 Ensure logging is configured | rsyslog current config message out"
        shell: cat /etc/rsyslog.conf
        become: yes
        changed_when: false
        failed_when: no
        register: rhel_07_4_2_1_4_audit

      - name: "4.2.1.4 Ensure logging is configured | Debug out rsyslog settings"
        debug:
            msg:
                - "These are the current logging configurations for rsyslog, please review:"
                - "{{ rhel_07_4_2_1_4_audit.stdout_lines }}"
        when:
            - not rhel7cis_rsyslog_ansiblemanaged

      - name: "4.2.1.4 Ensure logging is configured | Set logging settings lineinfile"
        lineinfile:
            path: /etc/rsyslog.conf
            state: present
            regexp: "{{ item.regexp }}"
            line: "{{ item.line }}"
            insertafter: '^[# ]*{{ item.insertafter }}\s*=\s*'
        with_items:
            - { regexp: '^\*\.emerg(.*)$', line: '*.emerg                                                 :omusrmsg:*', insertafter: '# Everybody gets emergency messages' }
            - { regexp: '^authpriv(.*)$', line: 'auth,authpriv.*                                              /var/log/secure', insertafter: '# # The authpriv file has restricted access.' }
            - { regexp: '^mail\.\*(.*)$', line: 'mail.*                                                  -/var/log/mail', insertafter: '# Log all the mail messages in one place.' }
            - { regexp: '^mail.info(.*)$', line: 'mail.info                                               -/var/log/mail.info', insertafter: '# Log all the mail messages in one place.' }
            - { regexp: '^mail.warning(.*)$', line: 'mail.warning                                            -/var/log/mail.warning', insertafter: '# Log all the mail messages in one place.' }
            - { regexp: '^mail.err(.*)$', line: 'mail.err                                                /var/log/mail.err', insertafter: '# Log all the mail messages in one place.' }
            - { regexp: '^news.crit(.*)$', line: 'news.crit                                               -/var/log/news/news.crit', insertafter: '# Save news errors of level crit and higher in a special file.' }
            - { regexp: '^news.err(.*)$', line: 'news.err                                             -/var/log/news/news.err', insertafter: '# Save news errors of level crit and higher in a special file.' }
            - { regexp: '^news.notice(.*)$', line: 'news.notice                                             -/var/log/news/news.notice', insertafter: '# Save news errors of level crit and higher in a special file.' }
        notify: restart rsyslog
        when:
            - rhel7cis_rsyslog_ansiblemanaged

      - name: "4.2.1.4 Ensure logging is configured | Misc. log setting"
        blockinfile:
            path: /etc/rsyslog.conf
            state: present
            marker: "# {mark} MISC. LOG SETTINGS (ANSIBLE MANAGED)"
            block: |
              # misc. logging additions to meet CIS standards
              *.=warning;*.=err                                        -/var/log/warn
              *.crit                                                   /var/log/warn
              *.*;mail.none;news.none                                  /var/log/messages
            insertafter: '#### RULES ####'
        notify: restart rsyslog
        when:
            - rhel7cis_rsyslog_ansiblemanaged

      - name: "4.2.1.4 Ensure logging is configured | Local log settings"
        blockinfile:
            path: /etc/rsyslog.conf
            state: present
            marker: "#{mark} LOCAL LOG SETTINGS (ANSIBLE MANAGED)"
            block: |
              # local log settings
              local0,local1.*                                          -/var/log/localmessages
              local2,local3.*                                          -/var/log/localmessages
              local4,local5.*                                          -/var/log/localmessages
              local6,local7.*                                          -/var/log/localmessages
            insertafter: '#### RULES ####'
        notify: restart rsyslog
  when:
      - rhel7cis_rule_4_2_1_4

- name: "4.2.1.5 Ensure rsyslog is configured to send logs to a remote log host"
  blockinfile:
      path: /etc/rsyslog.conf
      state: present
      block: |
        # remote host is: name/ip:port, e.g. 192.168.0.1:514, port optional
        *.* @@{{ rhel7cis_remote_log_server }}
        ##Set disk queue when rsyslog server will be down:

        $ActionQueueFileName queue
        $ActionQueueMaxDiskSpace 1g
        $ActionQueueSaveOnShutdown on
        $ActionQueueType LinkedList
        $ActionResumeRetryCount -1
      insertafter: EOF
  notify: restart rsyslog
  register: result
  failed_when:
      - result is failed
      - result.rc != 257
  when:
      - rhel7cis_rule_4_2_1_5
      - rhel7cis_remote_log_server is defined

- name: "4.2.1.6 Ensure remote rsyslog messages are only accepted on designated log hosts."
  block:
    - name: "4.2.1.6 Ensure remote rsyslog messages are only accepted on designated log hosts. | When not log host"
      replace:
        path: /etc/rsyslog.conf
        regexp: '({{ item }})'
        replace: '#\1'
      with_items:
        - '^(\$ModLoad imtcp)'
        - '^(\$InputTCPServerRun)'
      notify: restart rsyslog
      when:
        - not rhel7cis_system_is_log_server

    - name: "4.2.1.6 Ensure remote rsyslog messages are only accepted on designated log hosts. | When log host"
      replace:
        path: /etc/rsyslog.conf
        regexp: '^#(.*{{ item }}.*)'
        replace: '\1'
      with_items:
        - 'ModLoad imtcp'
        - 'InputTCPServerRun'
      notify: restart rsyslog
      when:
        - rhel7cis_system_is_log_server
  when:
    - rhel7cis_rule_4_2_1_6

- name: "4.2.2.1 Ensure journald is configured to send logs to rsyslog"
  lineinfile:
    path: /etc/systemd/journald.conf
    regexp: '^[F|f]orward[T|t]o[S|s]yslog='
    line: "ForwardToSyslog=yes"
  when:
    - rhel7cis_rule_4_2_2_1
    - ansible_facts['distribution_major_version'] != "6"

- name: "4.2.2.2 Ensure journald is configured to compress large log files"
  lineinfile:
    path: /etc/systemd/journald.conf
    regexp: '^[C|c]ompress='
    line: "Compress=yes"
  when:
    - rhel7cis_rule_4_2_2_2
    - ansible_facts['distribution_major_version'] != "6"

- name: "4.2.2.3 Ensure journald is configured to write logfiles to persistent disk"
  lineinfile:
    path: /etc/systemd/journald.conf
    regexp: '^[S|s]torage='
    line: "Storage=persistent"
  when:
    - rhel7cis_rule_4_2_2_3
    - ansible_facts['distribution_major_version'] != "6"

- name: "4.2.3 Ensure permissions on all logfiles are configured"
  command: find /var/log -type f -exec chmod g-wx,o-rwx "{}" + -o -type d -exec chmod g-wx,o-rwx "{}" +
  changed_when: no
  failed_when: no
  when:
    - rhel7cis_rule_4_2_3

- name: "4.2.4 Ensure logrotate is configured"
  find:
    paths: /etc/logrotate.d/
  register: log_rotates
  when:
    - rhel7cis_rule_4_2_4